---
platform: linux
image_resource:
  type: registry-image
  source: 
    repository: jasonmorgan/tanzue2e

inputs:
  - name: source
  - name: tanzu-e2e

params:
  TBS_KUBECONFIG:
  IMAGE_NAME:
  TAG:

run:
  path: "/bin/bash"
  args:
  - "tanzu-e2e/ci/tasks/handoff-to-tbs.sh"