---
platform: linux
image_resource:
  type: registry-image
  source: 
    repository: gcr.io/sys-2b0109it/demo/bitnami/java

inputs:
  - name: source
  - name: tanzu-e2e

params:

run:
  path: "/bin/bash"
  args:
  - "tanzu-e2e/ci/tasks/run-tests.sh"