resources:
- name: source
  type: git
  source:
    uri: https://github.com/jasonmorgan/spring-petclinic.git
- name: tanzu-e2e
  type: git
  source:
    uri: https://github.com/jasonmorgan/tanzu-e2e.git

jobs:
- name: testing
  plan:
  - get: source
    trigger: true
  - get: tanzu-e2e
  - task: run-tests
    file: tanzu-e2e/ci/tasks/run-tests.yaml
# - name: Compile
#   plan:
#   - get: source
#     trigger: true
#     passed: Testing
#   - get: tanzu-e2e
#   - task: compile-code
#     file: ci/tasks/compile.yaml
- name: build
  plan:
  - get: source
    trigger: true
    passed: 
    - testing
  - get: tanzu-e2e
  - task: compile-code
    file: tanzu-e2e/ci/tasks/compile.yaml
  - task: handoff-to-tbs
    params:
      TBS_KUBECONFIG: ((kubeconfig))
      IMAGE_NAME: ((image_name))
      TAG: ((tag))
      REG_USER: ((harbor.user))
      REG_PASS: ((harbor.password))
      REG_URL: ((harbor.reg))
    file: tanzu-e2e/ci/tasks/handoff-to-tbs.yaml
