resources:
- name: source
  type: git
  source:
    uri: https://github.com/jasonmorgan/spring-petclinic.git
- name: tanzu-e2e
  type: git
  source:
    uri: https://github.com/jasonmorgan/tanzu-e2e.git

jobs:
# - name: Tests
#   plan:
#   - get: petclinic
#   - task: unit
#     file: ci/tasks/unit-tests.yaml
- name: build
  plan:
  - get: source
  - get: tanzu-e2e
  # - task: build bin
  #   file: ci/tasks/compile.yaml
  - task: handoff-to-tbs
    params:
      TBS_KUBECONFIG: ((kubeconfig))
      IMAGE_NAME: ((image_name))
      TAG: ((tag))
      REG_USER: ((harbor.user))
      REG_PASS: ((harbor.password))
      REG_URL: ((harbor.reg))
    file: tanzu-e2e/ci/tasks/handoff-to-tbs.yaml
