resources:
- name: petclinic
  type: git
  source:
    uri: https://github.com/jasonmorgan/spring-petclinic.git
- name: tanzu-e2e
  type: git
  source:
    uri: https://github.com/jasonmorgan/tanzu-e2e.git

jobs:
# - name: Tests
#   plan:
#   - get: petclinic
#   - task: unit
#     file: ci/tasks/unit-tests.yaml
- name: Build
  plan:
  - get: petclinic
  - get: tanzu-e2e
  # - task: build bin
  #   file: ci/tasks/compile.yaml
  - task: handoff to TBS
    params:
      TBS_KUBECONFIG: ((kubeconfig))
      IMAGE_NAME: ((image_name))
    file: ci/tasks/handoff-to-tbs.yaml
